#include "GFXMODE.h"
#include "Define.h"

GFXMODE GFXMODE::GFXMODE_Control;

GFXMODE::GFXMODE() {
     GFX_MODE = GFX_MODE_PC;
}

int GFXMODE::GET_GFX_MODE() {
    return GFX_MODE;
}

void GFXMODE::CHANGE_GFX_MODE(int NEW_MODE) {
     if(NEW_MODE == GFX_MODE_PC) {GFX_MODE = GFX_MODE_PC;}
     if(NEW_MODE == GFX_MODE_8BIT) {GFX_MODE = GFX_MODE_8BIT;}
     if(NEW_MODE == GFX_MODE_16BIT) {GFX_MODE = GFX_MODE_16BIT;}
     if(NEW_MODE == GFX_MODE_64BIT) {GFX_MODE = GFX_MODE_64BIT;}
     if(NEW_MODE == GFX_MODE_PS2) {GFX_MODE = GFX_MODE_PS2;}
     if(NEW_MODE == GFX_MODE_CURRENT) {GFX_MODE = GFX_MODE_CURRENT;}
}
